# inspired from https://github.com/magnuslundstrom/test-db-orm-setup/blob/master/docker-compose.yml

version: '3.7'

services:
    db:
        image: mysql:5.7
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db-volume:/var/lib/mysql
        restart: always
        env_file:
            - db.env
        ports:
            - 3306:3306

    api:
        build: ${PWD}/api/.
        ports:
            - 4000:4000
        volumes:
            - ./api:/usr/api
        depends_on:
            - db
        env_file:
            - db.env

    listener:
        build: ${PWD}/listener/.
        ports:
            - 4080:4080
        volumes:
            - ./listener:/usr/listener
        depends_on:
            - db
        env_file:
            - db.env

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80

volumes:
    db-volume:
